name = "market-dashboard-worker"
main = "src/index.ts"
compatibility_date = "2026-06-29"

[vars]
CACHE_TTL_SECONDS = "86400"

[[d1_databases]]
binding = "DASHBOARD_DB"
database_name = "market-dashboard"
database_id = "add437f0-400f-49e1-8b39-0ea9beab050a"
